### ISSUE TITLE
Configurable access levels to support different user groups

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#10]
### User Story

A manager at UBDC would like the CKAN default roles to support different user groups

### Acceptance Criteria

- [ ] UBDC is able to make use of CKAN's default user roles

**Comment by sagargg** [comment]
@juanbrits Can you add more details?  what is required to do for this issue?

**Comment by juanbrits** [comment]
Hi @sagargg the users require the ability to use CKAN's default user roles. 
I hope this clears the issue up?

**Comment by sagargg** [comment]
@juanbrits  Ok, In that case i believe it's out of a box CKAN feature.  nothing to do here.

**Comment by sagargg** [comment]
**No action required**
