### ISSUE TITLE
Setup development environment in a separate project namespace

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#14]
Setup development environment in a separate project namespace

- [x] Install the latest CKAN version ckan v2.9.7

- [x] Use latest datapusher (0.0.18 - Python3)
- [x] Use Solr 8.1.1
- [x] Configure to restrict access user info to the public
- [x] Enable [ckanext-dataexplorer-react](https://github.com/datopian/ckanext-dataexplorer-react)
- [x] Testing
- [x] Integration testing
- [x] QA

**Comment by sagargg** [comment]
I belive this is also done so closing.
