### ISSUE TITLE
Frontend stack from client (branding guidelines )

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#15]
### Job Story

While I am exploring the UBDC Data Portal, I want to explore a portal that is in line with UBDC's branding guidelines so that I can easily identify the brand. 

### Acceptance Criteria

- [x] The UBDC brand guidelines are implemented on all pages ✅  Done 

### Tasks

- [ ] Client to share logos, CI, images for landing page

**Comment by sagargg** [comment]
Closing as **DONE**
