### ISSUE TITLE
UBDC Design

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#19]
### Job Story

When I explore the data portal, I want to explore a portal that is uniquely UBDC's so that the business can be promoted through portal usage.  

### Acceptance Criteria
* [x] I can see new design has been implemented on homepage. ✅  **Already implemented and deployed on  both staging and production env. https://data.ubdc.ac.uk/**
### Tasks

- [x] Design a frontend that is inline with the general UBDC website: https://www.ubdc.ac.uk/

**Comment by juanbrits** [comment]
[@Monika Popova](mailto:monika.popova@datopian.com) will progress with design work based on the general UBDC website (https://www.ubdc.ac.uk/) and Heather will provide any documentation if available.

**Comment by sagargg** [comment]
Closing as Done. Already implementead and deployed on both staging and production env.
 https://data.ubdc.ac.uk/ - Production env.
 https://ckan.ubdc.staging.datopian.com/ - Staging env.
