### ISSUE TITLE
ckanext-restricted throws an error whenever we do package_search

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#20]
Investigate and resolve bug found by Ismail through integration testing:

![image](https://user-images.githubusercontent.com/103997912/207278637-549c7678-3077-4a7d-9e87-5b85cf2d035d.png)

**Comment by sagargg** [comment]
@juanbrits  @MuhammadIsmailShahzad  This is fixed here 
https://github.com/datopian/ckanext-restricted/commit/84c2f7400e464ee44b18669c831cf9425d91448c

**Comment by sagargg** [comment]
@juanbrits  it can be closed. Already fixed

**Comment by sagargg** [comment]
Closing as already **FIXED**
